### ISSUE TITLE
Trying to compile http, but raphf giving problems

### ISSUE THREAD

**Issue by zico4reel** [m6w6/ext-raphf#7]
Hi, am trying to compile http on windows for php7.2, but for some reason each time i run configure with enable-raphf i get Microsoft Jscript Runtime, property or method not supportedl, I tried using pecl i get raphf.dsp not found please help

**Comment by zrmei** [comment]
I get same error
```batch
Checking for zlib.h ...  <in deps path> \include
Enabling extension ext\opcache [shared]
Enabling extension ext\pcre
Enabling extension ext\propro
Enabling extension ext\raphf
C:\temp\php-sdk\phpmaster\vc15\x64\php-src\configure.js(1602, 2) Microsoft JScript runtime error: Object does not support this property or method
```

**Comment by cmb69** [comment]
Did you try to build raphf-master? raphf-2.0.0 doesn't build on Windows, but there is a commit in master (49703f0c5cd041e8de7fbccefc4581605ddbba64) which may solve this.

@m6w6, are you planning to do a new raphf release? If that would build successfully, I could trigger pecl_http DLL builds.

**Comment by m6w6** [comment]
I could, but this only makes sense if it was already verified to build successfully?

**Comment by Jan-E** [comment]
It builds successfully now, also on Windows:
https://github.com/m6w6/ext-raphf/pull/8

I did not run the tests yet.

**Comment by Jan-E** [comment]
@cmb69 Could you try to build the DLL's for raphf master and http master? Preferably for PHP 7.1 up until PHP 7.4. My curl setup is not exactly standard, so I would like to see if pecl_http still supports curl in all those PHP-versions.

**Comment by cmb69** [comment]
I can confirm that current master builds on Windows for PHP 7.3. If a new release is made, the DLLs should be built fully automatically.

@Jan-E, no, I can't, since ext-http doesn't build for me (with or without m6w6/ext-http#96), because neither normaliz.lib or wldap32.lib are there. Furthermore, PHP 7.1 would require OpenSSL 1.0, which is apparently no longer support by ext-http.

**Comment by Jan-E** [comment]
normaliz.lib and wldap32.lib are being used for compiling the curl extension in PHP 7.4 as well:
https://github.com/php/php-src/blob/PHP-7.4/ext/curl/config.w32#L20

They should be there. Both are included in the Windows SDK's. On my system 34 versions of wldap32.lib are found. Examples:
```
 Directory of C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\ADL Tools\2.2.6000.1\CppSDK\SDK\lib

20/04/17  18:25            52.016 Wldap32.Lib
               1 File(s)         52.016 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\arm

28/03/16  22:42            52.008 Wldap32.Lib
               1 File(s)         52.008 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\arm64

28/03/16  23:42            52.016 Wldap32.Lib
               1 File(s)         52.016 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x64

28/03/16  23:01            52.016 Wldap32.Lib
               1 File(s)         52.016 bytes

 Directory of C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x86

28/03/16  23:03            53.218 Wldap32.Lib
               1 File(s)         53.218 bytes
```

**Comment by cmb69** [comment]
@Jan-E, indeed, you're right! I tried again, but neither icule.lib nor iculx.lib could be found. If I remove the respective checks, building current master of ext-http succeeds.

**Comment by Jan-E** [comment]
That should be OK now: https://github.com/m6w6/ext-http/commit/f94c237788db6949e7ea63f360ad45412de50267

**Comment by Jan-E** [comment]
> Furthermore, PHP 7.1 would require OpenSSL 1.0, which is apparently no longer support by ext-http.

Did you actually try to compile PHP 7.1? I did. This is a dump of the phpinfo:
https://phpdev.toolsforresearch.com/php-7.1.32-nts-Win32-VC14-x64.htm

Complete build:
https://phpdev.toolsforresearch.com/php-7.1.32-nts-Win32-VC14-x64.zip

**Comment by cmb69** [comment]
Thanks, @Jan-E! Indeed, everything's fine for 7.1 since the old libs are given as fallback.

**Comment by cmb69** [comment]
Since the build issue is fixed, I think this ticket can be closed (prebuilt DLLs are now [also available](https://pecl.php.net/package/raphf/2.0.1/windows)).

**Comment by Jan-E** [comment]
@cmb69 When will you start adding the PHP 7.4 DLL's to PECL?

**Comment by cmb69** [comment]
Snapshots are already supposed to be built and placed under https://windows.php.net/downloads/pecl/snaps/ (that build is just about to run for raphf). A mass rebuild is planned shortly after 7.4.0 is released (so the DLLs will be shown on the PECL pages).

**Comment by m6w6** [comment]
Hey, thanks you all!

I'm currently AFK, but I pushed the release yesterday.

Looks like we shoukd push another release for ext-http after the recent fixes?

So then the trio http/raphf/propro is okay then on windows?

**Comment by cmb69** [comment]
Yes, http/raphf/propro should currently be fine; a new ext-http release would be great.

**Comment by Jan-E** [comment]
ext-http still has some 30 test failures on Windows, but that has ever been so. I just checked 5.6.40...

Closing this, as a new ext-http release has been created.

**Comment by cmb69** [comment]
FTR, pecl_http still doesn't build on the PECL build machine; I'll have a closer look at this ASAP.

**Comment by m6w6** [comment]
Ah, yeah just noticed this, too

**Comment by Jan-E** [comment]
Is libevent installed on the pecl machine? I am compiling with 2.1.8-stable. Configure should circumvent it, but it might be the cause.

Anyway, @cmb69 can see what is wrong in configure,js, we can't.

**Comment by cmb69** [comment]
Yes, libevent 2.1.8 is installed and used. Line 1590 in configure.js is basically https://github.com/php/php-src/blob/php-7.3.11/win32/build/confutils.js#L1588; looks like file_list would be `false`.

**Comment by Jan-E** [comment]
Try adding this before the ADD_SOURCES line in config.w32

`WARNING("input for add_sources = " + PHP_HTTP_SOURCES);`

On my system it reports:
```
WARNING: input for add_sources =  php_http.c php_http_buffer.c php_http_client.c php_http_c
lient_curl.c php_http_client_curl_event.c php_http_client_curl_user.c php_http_client_reque
st.c php_http_client_response.c php_http_cookie.c php_http_curl.c php_http_encoding.c php_h
ttp_encoding_brotli.c php_http_encoding_zlib.c php_http_env.c php_http_env_request.c php_ht
tp_env_response.c php_http_etag.c php_http_exception.c php_http_filter.c php_http_header.c
php_http_header_parser.c php_http_info.c php_http_message.c php_http_message_body.c php_htt
p_message_parser.c php_http_misc.c php_http_negotiate.c php_http_object.c php_http_options.
c php_http_params.c php_http_querystring.c php_http_url.c php_http_version.c
```

**Comment by Jan-E** [comment]
The same line can be added to the config.w32 of propro and raphf, mutatis mutandis.

**Comment by Jan-E** [comment]
```
WARNING: PROPRO input for add_sources =  php_propro_api.c

WARNING: RAPHF input for add_sources =  php_raphf_api.c
```
Note that there is a space before the first file.

**Comment by cmb69** [comment]
Okay, the raphf issues are resolved (I had to update to 2.0.1 on the build bot; unfortunately this doesn't happen automatically yet); now pecl_http's `configure succeeds`, so I think this issue can be closed, and m6w6/ext-http#97 should be used to track remaining build issues.
